---
jobs:
- name: run tests
  plan:
  - get: github
    trigger: true
  - task: run tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: openjdk
      inputs:
      - name: github
        path: holy-guacamole
      run:
        path: sh
        dir: holy-guacamole
        args:
        - -exc
        - |
          ./gradlew test
      params:
        GRADLE_USER_HOME: /tmp/.gradle
      caches:
        - path: ../../.gradle/

- name: deploy test
  plan:
  - get: github
    trigger: true
    passed: [run tests]
  - put: heroku-test
    params:
      repository: github

- name: Digital Portfolio PROD
  plan:
  - get: heroku-test
    passed: [deploy test]
  - put: heroku-digital
    params:
      repository: heroku-test

- name: Product Solutions PROD
  plan:
  - get: heroku-test
    passed: [deploy test]
  - put: heroku-product
    params:
      repository: heroku-test

resources:
- name: github
  type: git
  source:
    uri: git@github.com:designed4device/holy-guacamole.git
    branch: master
    private_key: ((git-private-key))
- name: heroku-test
  type: git
  source:
    uri: ssh://git@heroku.com/holy-guacamole-test.git
    branch: master
    private_key: ((heroku-private-key))
- name: heroku-digital
  type: git
  source:
    uri: ssh://git@heroku.com/holy-guacamole.git
    branch: master
    private_key: ((heroku-private-key))
#heroku-product is the server for the hcscproduct slack workspace
- name: heroku-product
  type: git
  source:
    uri: ssh://git@heroku.com/holy-guacamole-product.git
    branch: master
    private_key: ((heroku-private-key))
